In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Sp3 / h1 : Distribucion de intervalos de clases

In [9]:
# Mayor a 20 

X = np.array([[22, 19, 16, 13, 18, 15, 20, 14, 15, 16], [15, 16, 20, 13, 15, 18, 15, 13, 18, 15]])
print(X)

count = X.shape[0] * X.shape[1] # total
print(count)

rango = np.max(X) - np.min(X) # rango
print(rango)

z = 1 + 3.322 * np.log10(count) # intervalo
print(z)

A = rango / z # amplitud
print(A)

[[22 19 16 13 18 15 20 14 15 16]
 [15 16 20 13 15 18 15 13 18 15]]
20
9
5.322021645595746
1.6910866958701634


#### Ejercicio tabla de frecuencias agrupadas en intervalos:

In [35]:
Xe = np.array([[58, 50, 56, 56, 58],
              [58, 56, 63, 50, 63],
              [68, 63, 64, 64, 53],
              [60, 68, 65, 63, 61],
              [55, 65, 56, 63, 52],
              [57, 60, 59, 58, 64]])
print(Xe)

r = np.max(Xe) - np.min(Xe)
print("\nRango: ", r)

z = np.floor(1 + 3.332 * np.log10(Xe.size)) # Redondeamos a impar (np.floor)
print("\nIntervalos: ", z)

A = np.round(r / z) # Redondeamos al mas cercano (np.round)
print("\nAmplitud:", A)

Nr = (A * z) - r # Nuevo rango
print("\nNuevo rango: ", Nr)

[[58 50 56 56 58]
 [58 56 63 50 63]
 [68 63 64 64 53]
 [60 68 65 63 61]
 [55 65 56 63 52]
 [57 60 59 58 64]]

Rango:  18

Intervalos:  5.0

Amplitud: 4.0

Nuevo rango:  2.0


In [57]:
rang = np.array([49, 53, 57, 61, 65, 69]) # Rango
print(rang)

Xi = np.array([51, 55, 59, 63, 67]) # lI - LS / 2 (Promedio marca de clase)
print(Xi)

f = np.array([3, 6, 8, 9, 4]) # Frecuencia (rango 4) f > X
print(f) # == total

frec, bins_edge = np.histogram(Xe, bins = rang) # Frecuencia definida por numpy
print(np.sum(frec)) 

fr = frec / np.sum(Xe.size) # Frecuencia relativa f1 / n
print(fr) # == 1

fA = np.array([3,9,17,26,30]) # Acumulacion de frecuencias 
print(fA) # == (3, 3+9, 3+9+8, 3+9+8+9, 3+9+8+9+4) 

[49 53 57 61 65 69]
[51 55 59 63 67]
[3 6 8 9 4]
30
[0.1        0.2        0.26666667 0.3        0.13333333]
[ 3  9 17 26 30]
